version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_HOST=n8n
      # - N8N_PATH=/n8n
      - N8N_EDITOR_BASE_URL=https://brief-eagerly-mutt.ngrok-free.app/
      - WEBHOOK_URL=https://brief-eagerly-mutt.ngrok-free.app/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - n8n_network 

volumes:
  n8n_data:

networks:
  n8n_network:
    external: true
