version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dandalonso@gmail.com
      PGADMIN_DEFAULT_PASSWORD: soft@123!
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data: